# setup files
DELETE_SETUP_FILES=true

ELECTRON_FOLDER_PATH="$HOME/.electron"
ELECTRON_FOLDER_PATH_VARIABLE="ELECTRON"
APPLICATIONS_FOLDER_PATH="$HOME/Applications"
APPLICATIONS_FOLDER_PATH_VARIABLE="APPLICATIONS_FOLDER"


# .electron folder
CONFIG_FILE_NAME=".configrc"


# setup
GOOGLE_CHROME="latest"
BRAVE_BROWSER="latest"
